const express = require('express');
const router = express.Router();
const newsController = require('../controllers/newsController');
const { authenticateToken, authorizeRoles, optionalAuth } = require('../middleware/auth');
const { trackActivity } = require('../middleware/activityTracker');
router.get('/', optionalAuth, newsController.getArticles);
router.get('/id/:id', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), newsController.getArticleById);
router.get('/:slug', optionalAuth, trackActivity('VIEW', 'article'), newsController.getArticleBySlug);
router.post('/', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), newsController.createArticle);
router.put('/:id', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), newsController.updateArticle);
router.delete('/:id', authenticateToken, authorizeRoles('ADMIN'), newsController.deleteArticle);
module.exports = router;
