const express = require('express');
const router = express.Router();
const sectionController = require('../controllers/sectionController');
const { authenticateToken, authorizeRoles } = require('../middleware/auth');
router.get('/', sectionController.getAllSections);
router.post('/', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), sectionController.createSection);
router.put('/:id', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), sectionController.updateSection);
router.delete('/:id', authenticateToken, authorizeRoles('ADMIN'), sectionController.deleteSection);
router.post('/subsections', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), sectionController.createSubsection);
router.put('/subsections/:id', authenticateToken, authorizeRoles('ADMIN', 'EDITOR'), sectionController.updateSubsection);
router.delete('/subsections/:id', authenticateToken, authorizeRoles('ADMIN'), sectionController.deleteSubsection);
router.get('/:id/subsections', sectionController.getSubsectionsBySectionId);
module.exports = router;
