const express = require('express');
const router = express.Router();
const { upload, uploadImage, uploadMultipleImages, deleteFile } = require('../controllers/uploadController');
const { authenticateToken, authorizeRoles } = require('../middleware/auth');
router.use(authenticateToken);
router.use(authorizeRoles('ADMIN', 'EDITOR'));
router.post('/image', upload.single('image'), uploadImage);
router.post('/images', upload.array('images', 10), uploadMultipleImages);
router.delete('/file', deleteFile);
module.exports = router;
